export const FETCH_IMAGES_REQUEST = "FETCH_IMAGES_REQUEST";
export const FETCH_IMAGES_FAILURE = "FETCH_IMAGES_FAILURE";
export const FETCH_IMAGES_SUCCESS = "RECEIVE_IMAGES";


export const FETCH_IMAGE_REQUEST = "FETCH_IMAGE_REQUEST";
export const FETCH_IMAGE_FAILURE = "FETCH_IMAGE_FAILURE";
export const FETCH_IMAGE_SUCCESS = "RECEIVE_IMAGE";